### ISSUE TITLE
Random hopping

### ISSUE THREAD

**Issue by empyriumz** [dean0x7d/pybinding#3]
Hi,

Is it possible to generate randomized hopping amplitude?
It is feasible in kwant by defining a function which generates a 
random number and then call it in the definitions of hoppings.
I tried this on pybinding but it returns the uniform hopping, i.e., 
the function is only called once then every sites are connected by
the same hopping amplitude.

Attached below is the snippet of my code

```python
import pybinding as pb
import numpy as np

def random_hopping(mu):
    return np.random.normal(mu, 1)


def chain_lattice(d, mu):
    lat = pb.Lattice(a1=[d])
    lat.add_sublattices(('A', [0]))
    lat.add_hoppings( ([0, 1], 'A', 'A', random_hopping(mu)),
    ([1, 0], 'A', 'A', random_hopping(mu)))
    return lat

lattice = chain_lattice(d=0.1,mu=0)
model = pb.Model(
    lattice,
    pb.primitive(a1=20)
)
```
The resulting finite size model shows that
all the hopping matrix elements are the same.

Thx~

**Comment by dean0x7d** [comment]
Hi @empyriumz,

It's possible. Like with any function-dependent onsite or hopping energy in pybinding, you just need a modifier function:

```python
import pybinding as pb
import numpy as np


def chain_lattice(d):
    lat = pb.Lattice(a1=[d])
    lat.add_sublattices(("A", [0]))
    lat.add_hoppings(([1], "A", "A", 1.0))
    return lat


def random_hopping(mu):
    @pb.hopping_energy_modifier
    def func(energy):
        return np.random.normal(mu, 1, size=energy.size)  # size is required
    return func


model = pb.Model(
    chain_lattice(d=0.1),
    pb.primitive(a1=6),
    random_hopping(mu=0)
)
```

The model creation process in pybinding is a bit different than kwant. In pybinding, the initial unit cell is created as a constant (usually this represents the pristine material). Any functions which need to be applied to multiple unit cells are introduced using modifiers (which act on the pristine material). 

Note that the `size` argument was given to `np.random.normal` so that it returns an array of random numbers instead of just a single one. This is because the modifier functions in pybinding are applied to all sites/hoppings at the same time (as numpy array operations), as opposed to kwant which applies one site/hopping at a time.

See this tutorial page for more information about modifier functions: http://docs.pybinding.site/en/stable/tutorial/fields.html

**Comment by empyriumz** [comment]
Hi @dean0x7d,

Great it works! Thx a lot.
