### ISSUE TITLE
installation with pip fails

### ISSUE THREAD

**Issue by rpoteau** [dean0x7d/pybinding#49]
Hello
the installation fails. The final message says

      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybinding
  Running setup.py clean for pybinding
Failed to build pybinding
ERROR: Could not build wheels for pybinding, which is required to install pyproject.toml-based projects

Thank you for your help
Romuald

**Comment by BertJorissen** [comment]
Hi Romuald
this error is a generic error that the compilation on your system didn't work.
Can you specify the operating system and python version?
If pip cannot find a pre compiled version, it will try to compile it. This message just says that it didn't work.
Now you have two options:

1. use the new (development) version that has a lot of pre compiled versions by `pip install -i https://test.pypi.org/simple/ pybinding`
2. provide a more detailed error message so that we can know what didn't work

I would only say to compile from source when you're doing quite intensive calculations, where you're running pybinding for hours on a cluster.
The first option is perfect for just configuring a system and doing smaller-scale caltulations.
Anyway, when you really want to have a fast and preformant calculation, you'll need to have a look at the quantum-KITE project.
Let me know if the first option worked out for you.
Best
Bert

**Comment by rpoteau** [comment]
Hi Bert
    
    thanks for this very fast answer :-)
    I am working under linux, my OS is the opensuse rolling release, aka
    Tumbleweed.
    pip --version returns:
    pip 23.2.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
    
    and please find enclosed the whole error output
    
    Best
    Romuald
    
    Le 11/11/2023 à 21:02, Bert Jorissen a
      écrit :
    
    
      
      Hi Romuald
        this error is a generic error that the compilation on your
        system didn't work.
        Can you specify the operating system and python version?
        If pip cannot find a pre compiled version, it will try to
        compile it. This message just says that it didn't work.
        Now you have two options:
      
        use the new (development) version that has a lot of pre
          compiled versions by pip install -i
            https://test.pypi.org/simple/ pybinding
        provide a more detailed error message so that we can know
          what didn't work
      
      I would only say to compile from source when you're
        doing quite intensive calculations, where you're running
        pybinding for hours on a cluster.
        The first option is perfect for just configuring a system and
        doing smaller-scale caltulations.
        Anyway, when you really want to have a fast and preformant
        calculation, you'll need to have a look at the quantum-KITE
        project.
        Let me know if the first option worked out for you.
        Best
        Bert
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dean0x7d/pybinding/issues/49#issuecomment-1806905212",
"url": "https://github.com/dean0x7d/pybinding/issues/49#issuecomment-1806905212",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BertJorissen** [comment]
Did the installation of the new version work?
Otherwise, you'll have to add the `pip install pybinding --verbose` option for the full logs.
Your mails will be displayed on the public GitHub automatically, and I couldn't see your attachment.
Bert

**Comment by rpoteau** [comment]
Hi again
yes; it works :-)
Thanks a lot
Best
Romuald
