### ISSUE TITLE
ldos breaks symmetry after slight system size increase

### ISSUE THREAD

**Issue by oroszl** [dean0x7d/pybinding#6]
As seen in [this](https://gist.github.com/oroszl/478a2813fa7cb13a93879b350868286c) gist a symmetry present in the local dos suddenly breaks down at a given system size.

**Comment by dean0x7d** [comment]
Thanks for reporting this! It should be fixed now in 867b7417650039f9b0f5ae40409cb2ad47528840.

This turned out to be a subtle but very serious issue specific to large multi-orbital models. In order to reduce RAM usage when building large systems, pybinding slices the work up into smaller pieces and buffers some intermediate hopping data. All the system slices have the same size except for the last one. This wasn't a problem for single-orbital models, but multi-orbital ones needed a buffer layout change in addition to the size change for that last slice. This is why the bug appeared in your example only after a certain size and for one side of the system (the last slice).

**Comment by oroszl** [comment]
Great, the day is saved !
Can confirm now that the freshest pull from github !
